#!/bin/bash

prooffile=`mktemp`
claimfile=`mktemp`

result=`sed 1q "$1"`
sed -n '1!p' "$1" > "$prooffile"

if [ "$result" = "YES" ]; then
	claim='<terminating/>'
elif [ "$result" = "NO" ]; then
	claim='<nonterminating/>'
else
	claim=
fi

if [ "$claim" != "" ]; then
	echo $claim > "$claimfile"
	cert=`./ceta "$2" "$claimfile" "$prooffile" 2> /dev/null`
	echo starexec-result=$cert $result
	echo result=$result
	echo certification-result=$cert
else
	echo starexec-result=$result
	echo result=$result
fi


rm "$prooffile"
rm "$claimfile"
