#!/bin/bash

result=`sed 1q "$1"`
echo bare-result=$result

sed -n '1!p' -i "$1"

if [ "$result" = "CERTIFIED YES" ]; then
	claim='<terminating/>'
	result=YES
elif [ "$result" = "CERTIFIED NO" ]; then
	claim='<nonterminating/>'
	result=NO
else
	claim=
fi

if [ -n "$claim" -a -f "$3/cpf.xml" ]; then
	claimfile=`mktemp`
	errfile=`mktemp`
	timefile=`mktemp`
	echo $claim > "$claimfile"
	cert=`/usr/bin/time --quiet -o "$timefile" -f %U ./ceta "$2" "$claimfile" "$1" 2> "$errfile"`
	echo starexec-result=$cert $result
	echo certification-result=$cert
	echo certification-err=`cat "$errfile"`
	echo certification-time=`cat "$timefile"`
	rm "$claimfile" "$errfile" "$timefile"
else
	echo starexec-result=$result
fi
